### ISSUE TITLE
FirmwareBundle for iPad4,4 iOS 11.4.1 

### ISSUE THREAD

**Issue by chelaxian** [marijuanARM/Inferius#11]
I see iPad4,5_11.4.1_bundle in /resources/FirmwareBundles.
Can I use it to restore iPad4,4 iOS 11.4.1 with only fixing Info.json file ?
Or patch files must be unique and different anyway?

**Comment by LukeZGD** [comment]
AFAIK yes actually
Just like how iPhone6,1 and iPhone6,2 bundles are identical (iphone6), it should be the same for iPad4,4, iPad4,5, and iPad4,6 (ipad4b)
Also I noticed the processor in Info.plist is wrong, should be S5L8960 (not sure if it matters as I haven't tried this yet)

**Comment by marijuanARM** [comment]
Sorry about the late response, but i'll create a bundle tonight. Will leave the issue open for now.

**Comment by chelaxian** [comment]
@LukeZGD thanks for answer, i'll fix processor in Info.json
@marijuanARM good news! and thanks for fixing instructions in Readme.

**Comment by marijuanARM** [comment]
Fixed in 06bb893.
