### ISSUE TITLE
No script "restituere.py" in master archive

### ISSUE THREAD

**Issue by chelaxian** [marijuanARM/Inferius#12]
I successfully created custom IPSW with script "inferius.py" that was presented in master archive of Inferius.
Next step I need is running script "restituere.py" to restore custom IPSW to my device.
But I can't find this script in master archive.
Where I can find it?
Thanks!

**Comment by chelaxian** [comment]
should I use "inferius_restore.py" instead of "restituere.py" ?

**Comment by marijuanARM** [comment]
The Inferius & Restituere scripts have been merged into one Inferius script, download the latest version of Inferius and use the Inferius script to restore.
