### ISSUE TITLE
Pwned DFU mode

### ISSUE THREAD

**Issue by chelaxian** [marijuanARM/Inferius#13]
`Is your device is connected in Pwned DFU mode with signature checks removed? [Y/N]: Y
[VERBOSE] Checking if device is in pwnrecovery...
[ERROR] Device did not enter recovery mode successfully! Make sure your device is in Pwned DFU mode with signature checks removed, then run this script again.
Exiting...`

Now, when I try to restore my custom IPSW i faced problem with putting device into Pwned DFU mode.
I can manually put it into common DFU mode, but not Pwned DFU.

Did you include instruments for putting device into Pwned DFU mode in master archive?
Should script Infernus.py calls it by itselfs?
Or I need to search and use for Pwned DFU some 3rd party tools like axi0mX/ipwndfu

**Comment by marijuanARM** [comment]
Inferius will not enter Pwned DFU for you, you must enter it on your own (with another tool).
