### ISSUE TITLE
SHSH didn't save! Make sure you're connected to the internet

### ISSUE THREAD

**Issue by chelaxian** [marijuanARM/Inferius#14]
Put iPad in Pwned DFU with ipwndfu or pyboot. New error about SHSH and Internet connection. But internet is ok.

**Comment by chelaxian** [comment]
MacBook-Air-chelaxian:Inferius-master chelaxian$ /Users/chelaxian/Desktop/inferius.sh -Y
[VERBOSE] Verifying device iPad4,4 exists...
[VERBOSE] Device iPad4,4 exists!
[VERBOSE] Verifying iOS 11.4.1 exists for device iPad4,4...
[VERBOSE] iOS 11.4.1 exists for device iPad4,4!
[VERBOSE] Cleaning out work/ directory
[VERBOSE] Finding Fimware Bundle for iPad4,4, 11.4.1
[VERBOSE] Firmware bundle exists at: resources/FirmwareBundles/iPad4,4_11.4.1_bundle
[VERBOSE] Checking if device is A9...
[VERBOSE] Device is not A9, continuing...
Is your device is connected in Pwned DFU mode with signature checks removed? [Y/N]: Y
Fetching some required info...
[VERBOSE] Fetching ECID...
[VERBOSE] ECID: 0x2b50e919fd4
[VERBOSE] Fetching apnonce...
[VERBOSE] apnonce: b803b8b5bbb727ebcd70f705f1f03eb45ceeca08
[ERROR] SHSH didn't save! Make sure you're connected to the internet, then try again.
Exiting...

**Comment by marijuanARM** [comment]
Can you upload the file `resources/Inferius-<date>.log`?
