### ISSUE TITLE
Request - Ipad Pro 9.7 A1674 iOS 13.7

### ISSUE THREAD

**Issue by TOTALMICHEL** [marijuanARM/Inferius#15]
Im sorry for asking where for this bundle. but i can't create it. im just not that handy about this stuff.
can you please create it? 
Again, sorry for taking some of your time for this request.

**Comment by marijuanARM** [comment]
I can create the bundle, but it won't be able to be restored due to the iOS 14 SEP not being compatible with iOS 13.7.

If you still want the bundle, I can create it though.

**Comment by TOTALMICHEL** [comment]
Thanks, i tought iOS 14 SEP was compatible (because i saw dual boot between iOS 13.7 and 14.
I was prepared To lose Touch ID, but if it can’t actually Restore, theres no point To it :/
Thanks anyway

Enviado do meu iPhone

No dia 03/10/2020, às 23:50, adam <notifications@github.com> escreveu:

﻿

I can create the bundle, but it won't be able to be restored due to the iOS 14 SEP not being compatible with iOS 13.7.

If you still want the bundle, I can create it though.

**Comment by UInt2048** [comment]
> iOS 14 SEP not being compatible with iOS 13.7.

Minor correction: according to [/r/iOSDowngrade](https://www.reddit.com/r/iOSDowngrade/comments/j1x7iv/downgrade_and_dualboot_status_of_almost_all_ios/), iOS 14 baseband isn't, but the SEP is down to iOS 13.5.

However, it seems that the baseband does make a difference for your iPad Pro 9.7-inch (I also own one), @TOTALMICHEL, because yours is a WiFi + Cellular, instead of WiFi-only like mine.

---

You may still be able to dual-boot it.

**Comment by TOTALMICHEL** [comment]
i did managed Before To downgrade older devices by swapping baseband files on Ipsw.
Can you please create the firmware bundle?

**Comment by UInt2048** [comment]
@marijuanARM It looks like they still want it...

**Comment by marijuanARM** [comment]
currently can't make a bundle, as there's no public keys available & i don't have an A9X device to decrypt keys with. If you can decrypt & provide iBSS & iBEC keys from [this](https://ipsw.me/download/iPad6,4/17H35) IPSW, then I can make a bundle for you.

**Comment by marijuanARM** [comment]
Didn't notice until now, but there's also no way to enter pwned DFU on A9X devices. Closing this issue for now.

**Comment by yusufklncc** [comment]
> Didn't notice until now, but there's also no way to enter pwned DFU on A9X devices. Closing this issue for now.

hi. we can enter pwned dfu mode via Gaster. is there any way decrypt keys? actually 15.7 versiyon is decryptable. but when I try iOS 15.6 or 14.3 I get this error. 
![image](https://user-images.githubusercontent.com/78423442/215279239-65b4b1e7-c2ee-41bc-80b9-30cd4e5b9e43.png)
