### ISSUE TITLE
AttributeError: 'Namespace'

### ISSUE THREAD

**Issue by tolikes** [marijuanARM/Inferius#24]
[VERBOSE] Verifying device iPhone9,1 exists...
[VERBOSE] Device iPhone9,1 exists!
[VERBOSE] Verifying iOS 12.4 exists for device iPhone9,1...
[VERBOSE] iOS 12.4 exists for device iPhone9,1!
[VERBOSE] Finding Firmware Bundle for iPhone9,1, 12.4
[VERBOSE] Firmware bundle exists at: resources/FirmwareBundles/iPhone9,1_12.4_bundle
[VERBOSE] Checking if device is A9...
[VERBOSE] Device is not A9, continuing...
Traceback (most recent call last):
  File "/Users/tolikes/Desktop/Inferius-master/./inferius.py", line 194, in <module>
    if args.update:
AttributeError: 'Namespace' object has no attribute 'update'

**Comment by marijuanARM** [comment]
fixed
