### ISSUE TITLE
Make a FirmwareBundle Generator

### ISSUE THREAD

**Issue by IIWare** [marijuanARM/Inferius#8]
some people while making firmwarebundle can be complex for them so for example when someone plugs in iDevice to mac, a script automatically takes info from iDevice and generates FirmwareBundle that matches the iPhone, but before the script has successfuly generated the FirmwarBundle it asks the user the iOS version they want to downgrade to (13.5) then the firmwarebundle is now generated and the downgrade process can be started. (sorry for bad grammar btw)

**Comment by NotHereForTheDong** [comment]
You must understand the complexity behind the bundles themselves before making such an absurd request. This isn’t possible to automate at the moment and would require immense work to even begin to automate. Closing this issue is it’s not valid

**Comment by IIWare** [comment]
@NotHereForTheDong ok I am sorry, then I will **try** to make my own FirmwareBundle Generator.

**Comment by IIWare** [comment]
@NotHereForTheDong why you give me a thumbs down?
